add_test( hw03_contact_number /home/jojo/JoaquimK_tasks/hw03/tests/hw03/testhw03 [==[--test-case=contact_number]==])
set_tests_properties( hw03_contact_number PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw03/tests/hw03)
add_test( hw03_contact_name /home/jojo/JoaquimK_tasks/hw03/tests/hw03/testhw03 [==[--test-case=contact_name]==])
set_tests_properties( hw03_contact_name PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw03/tests/hw03)
add_test( hw03_add_contact /home/jojo/JoaquimK_tasks/hw03/tests/hw03/testhw03 [==[--test-case=add_contact]==])
set_tests_properties( hw03_add_contact PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw03/tests/hw03)
add_test( hw03_remove_contact /home/jojo/JoaquimK_tasks/hw03/tests/hw03/testhw03 [==[--test-case=remove_contact]==])
set_tests_properties( hw03_remove_contact PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw03/tests/hw03)
add_test( hw03_sort_contacts /home/jojo/JoaquimK_tasks/hw03/tests/hw03/testhw03 [==[--test-case=sort_contacts]==])
set_tests_properties( hw03_sort_contacts PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw03/tests/hw03)
set( testhw03_TESTS hw03_contact_number hw03_contact_name hw03_add_contact hw03_remove_contact hw03_sort_contacts)
