add_test( [==[hw05_Creating tokens]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Creating tokens]==])
set_tests_properties( [==[hw05_Creating tokens]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Test valid SQL queries]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Test valid SQL queries]==])
set_tests_properties( [==[hw05_Test valid SQL queries]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Test invalid SQL queries]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Test invalid SQL queries]==])
set_tests_properties( [==[hw05_Test invalid SQL queries]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from Start state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from Start state]==])
set_tests_properties( [==[hw05_Transition from Start state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from SelectStmt state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from SelectStmt state]==])
set_tests_properties( [==[hw05_Transition from SelectStmt state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from AllColumns state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from AllColumns state]==])
set_tests_properties( [==[hw05_Transition from AllColumns state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from NamedColumn state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from NamedColumn state]==])
set_tests_properties( [==[hw05_Transition from NamedColumn state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from MoreColumns state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from MoreColumns state]==])
set_tests_properties( [==[hw05_Transition from MoreColumns state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from FromClause state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from FromClause state]==])
set_tests_properties( [==[hw05_Transition from FromClause state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from TableName state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from TableName state]==])
set_tests_properties( [==[hw05_Transition from TableName state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from Valid state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from Valid state]==])
set_tests_properties( [==[hw05_Transition from Valid state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
add_test( [==[hw05_Transition from Invalid state]==] /home/jojo/JoaquimK_tasks/hw05/tests/hw05/testhw05 [==[--test-case=Transition from Invalid state]==])
set_tests_properties( [==[hw05_Transition from Invalid state]==] PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw05/tests/hw05)
set( testhw05_TESTS [==[hw05_Creating tokens]==] [==[hw05_Test valid SQL queries]==] [==[hw05_Test invalid SQL queries]==] [==[hw05_Transition from Start state]==] [==[hw05_Transition from SelectStmt state]==] [==[hw05_Transition from AllColumns state]==] [==[hw05_Transition from NamedColumn state]==] [==[hw05_Transition from MoreColumns state]==] [==[hw05_Transition from FromClause state]==] [==[hw05_Transition from TableName state]==] [==[hw05_Transition from Valid state]==] [==[hw05_Transition from Invalid state]==])
