add_test( hw04_vm_direct_return /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_direct_return]==])
set_tests_properties( hw04_vm_direct_return PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_pop /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_pop]==])
set_tests_properties( hw04_vm_pop PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_add /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_add]==])
set_tests_properties( hw04_vm_add PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_div /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_div]==])
set_tests_properties( hw04_vm_div PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_eq /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_eq]==])
set_tests_properties( hw04_vm_eq PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_neq /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_neq]==])
set_tests_properties( hw04_vm_neq PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_dup /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_dup]==])
set_tests_properties( hw04_vm_dup PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_write /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_write]==])
set_tests_properties( hw04_vm_write PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_write_char /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_write_char]==])
set_tests_properties( hw04_vm_write_char PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_jmp /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_jmp]==])
set_tests_properties( hw04_vm_jmp PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_jmpz /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_jmpz]==])
set_tests_properties( hw04_vm_jmpz PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_illegal_instruction /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_illegal_instruction]==])
set_tests_properties( hw04_vm_illegal_instruction PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_custom_instructions /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_custom_instructions]==])
set_tests_properties( hw04_vm_custom_instructions PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_stack_failure /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_stack_failure]==])
set_tests_properties( hw04_vm_stack_failure PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
add_test( hw04_vm_segfault /home/jojo/JoaquimK_tasks/hw04/tests/hw04/testhw04 [==[--test-case=vm_segfault]==])
set_tests_properties( hw04_vm_segfault PROPERTIES WORKING_DIRECTORY /home/jojo/JoaquimK_tasks/hw04/tests/hw04)
set( testhw04_TESTS hw04_vm_direct_return hw04_vm_pop hw04_vm_add hw04_vm_div hw04_vm_eq hw04_vm_neq hw04_vm_dup hw04_vm_write hw04_vm_write_char hw04_vm_jmp hw04_vm_jmpz hw04_vm_illegal_instruction hw04_vm_custom_instructions hw04_vm_stack_failure hw04_vm_segfault)
